apiVersion: "nais.io/v1alpha1"
kind: "Application"
metadata:
  name: flexjar-backend
  namespace: flex
  labels:
    team: flex
spec:
  image: {{image}}
  replicas:
    min: {{replicas_min}}
    max: {{replicas_max}}
    scalingStrategy:
      cpu:
        thresholdPercentage: 90
  port: 8080
  liveness:
    path: /internal/health/liveness
  readiness:
    path: /internal/health/readiness
  startup:
    path: /internal/health/liveness
    initialDelay: 40
  prometheus:
    enabled: true
    path: /internal/prometheus
  resources:
    limits:
      memory: {{memory}}
    requests:
      cpu: {{cpu}}
      memory: {{memory}}
  tokenx:
    enabled: true
  azure:
    application:
      tenant: nav.no
      enabled: true
      allowAllUsers: true
  gcp:
    sqlInstances:
      - type: POSTGRES_14
        tier: {{db_tier}}
        diskType: SSD
        highAvailability: true
        diskSize: 10
        pointInTimeRecovery: false
        diskAutoresize: true
        databases:
          - name: flexjar-backend-db
            envVarPrefix: DATABASE
            users:
              - name: bigquery-datastream
        maintenance:
          day: 2
          hour: 2
        flags:
          - name: cloudsql.logical_decoding
            value: "on"
  accessPolicy:
    inbound:
      rules:
        - application: sykepengesoknad
        - application: flexjar-frontend
        - application: spinnsyn-frontend
        - application: ditt-sykefravaer
        - application: dinesykmeldte
          namespace: teamsykmelding
        - application: sykmeldinger
          namespace: teamsykmelding
        - application: spinntektsmelding-frontend
          namespace: helsearbeidsgiver
        - application: flexjar-proxy
          namespace: tbd
        - application: syfomodiaperson
          namespace: teamsykefravr
        - application: syfooversikt
          namespace: teamsykefravr
  env:
  {{#each env}}
     - name: {{@key}}
       value: "{{this}}"
  {{/each}}
