apiVersion: "nais.io/v1alpha1"
kind: "Application"
metadata:
  name: flexjar-backend
  namespace: flex
  labels:
    team: flex
spec:
  image: {{image}}
  replicas:
    min: {{replicas_min}}
    max: {{replicas_max}}
    scalingStrategy:
      cpu:
        thresholdPercentage: 90
  port: 8080
  liveness:
    path: /internal/health/liveness
  readiness:
    path: /internal/health/readiness
  startup:
    path: /internal/health/liveness
    initialDelay: 40
  prometheus:
    enabled: true
    path: /internal/prometheus
  resources:
    limits:
      memory: {{memory}}
    requests:
      cpu: {{cpu}}
      memory: {{memory}}
  tokenx:
    enabled: true
  azure:
    application:
      tenant: nav.no
      enabled: true
      allowAllUsers: false
      claims:
        groups:
          - id: "5206a646-a99e-4cd5-90e4-758cf7948cc8" #flex
          - id: "020e6140-6395-430b-9021-65de50e42a0f" #flexjar
          - id: "3a541678-8965-45c4-844b-486a8b9b94a3" #teamsykmelding
          - id: "6b8065ba-98e2-4e2d-98d4-f9768c7fbb38" #helsearbeidsgiver
          - id: "c0227409-2085-4eb2-b487-c4ba270986a3" #tbd
  gcp:
    sqlInstances:
      - type: POSTGRES_14
        tier: {{db_tier}}
        diskType: SSD
        highAvailability: true
        diskSize: 10
        pointInTimeRecovery: false
        diskAutoresize: true
        databases:
          - name: flexjar-backend-db
            envVarPrefix: DATABASE
            users:
              - name: bigquery-datastream
        maintenance:
          day: 2
          hour: 2
        flags:
          - name: cloudsql.logical_decoding
            value: "on"
  accessPolicy:
    inbound:
      rules:
        - application: sykepengesoknad
        - application: flexjar-frontend
        - application: spinnsyn-frontend
        - application: ditt-sykefravaer
        - application: dinesykmeldte
          namespace: teamsykmelding
        - application: sykmeldinger
          namespace: teamsykmelding
        - application: spinntektsmelding-frontend
          namespace: helsearbeidsgiver
        - application: flexjar-proxy
          namespace: tbd
  env:
  {{#each env}}
     - name: {{@key}}
       value: "{{this}}"
  {{/each}}
